/* Generated by tools/build.py from js/*.js. Do not edit. */
/* --- js/main.js --- */
/* ============================================================
   Main JavaScript   Navbar, Mobile Menu, Smooth Scroll,
   FAQ Accordion, Roadmap Scroll
   ============================================================ */

(function () {
  'use strict';

  // -- Navbar scroll behavior --------------------------------
  const navbar = document.querySelector('.navbar');

  function handleNavbarScroll() {
    if (!navbar) return;
    if (window.scrollY > 50) {
      navbar.classList.add('scrolled');
    } else {
      navbar.classList.remove('scrolled');
    }
  }

  window.addEventListener('scroll', handleNavbarScroll, { passive: true });
  handleNavbarScroll(); // initial check

  // -- Mobile menu toggle ------------------------------------
  const toggle = document.querySelector('.navbar-toggle');
  const mobileNav = document.querySelector('.navbar-nav');

  if (toggle && mobileNav) {
    function setMenu(open) {
      toggle.classList.toggle('open', open);
      mobileNav.classList.toggle('open', open);
      toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
      toggle.setAttribute('aria-label', open ? 'Close navigation menu' : 'Open navigation menu');
      document.body.style.overflow = open ? 'hidden' : '';
    }

    toggle.addEventListener('click', function () {
      setMenu(!toggle.classList.contains('open'));
    });

    // Close when any menu link (including the CTA) is used
    mobileNav.querySelectorAll('a').forEach(function (link) {
      link.addEventListener('click', function () { setMenu(false); });
    });

    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && toggle.classList.contains('open')) {
        setMenu(false);
        toggle.focus();
      }
    });

    // Leaving the mobile layout with the menu open would leave the page scroll-locked
    window.matchMedia('(min-width: 1100px)').addEventListener('change', function (e) {
      if (e.matches) setMenu(false);
    });
  }

  // -- Smooth scroll for anchor links ------------------------
  document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
    anchor.addEventListener('click', function (e) {
      const targetId = this.getAttribute('href');
      if (targetId === '#') return;
      const target = document.querySelector(targetId);
      if (target) {
        e.preventDefault();
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });

  // -- FAQ Accordion Toggle -------------------------------
  function initFaqAccordion() {
    const faqItems = document.querySelectorAll('.faq-question');
    if (!faqItems.length) return;

    faqItems.forEach(function (btn, i) {
      var item = btn.closest('.faq-item');
      var answer = item && item.querySelector('.faq-answer');
      if (answer) {
        if (!answer.id) answer.id = 'faq-answer-' + (i + 1);
        btn.setAttribute('aria-controls', answer.id);
      }
      btn.setAttribute('aria-expanded', item && item.classList.contains('active') ? 'true' : 'false');

      // Native <button> already handles Enter and Space
      btn.addEventListener('click', function () {
        var isOpen = item.classList.toggle('active');
        btn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
        if (answer) {
          answer.style.display = isOpen ? 'block' : 'none';
        }
      });
    });
  }

  initFaqAccordion();

  // -- Roadmap Scroll Indicators ------------------------------
  function initRoadmapScroll() {
    const roadmapWrapper = document.querySelector('.roadmap-wrapper');
    const scrollLeftBtn = document.querySelector('.roadmap-scroll-indicator.left');
    const scrollRightBtn = document.querySelector('.roadmap-scroll-indicator.right');

    if (roadmapWrapper && (scrollLeftBtn || scrollRightBtn)) {
      if (scrollLeftBtn) {
        scrollLeftBtn.addEventListener('click', function () {
          roadmapWrapper.scrollBy({ left: -250, behavior: 'smooth' });
        });
      }
      if (scrollRightBtn) {
        scrollRightBtn.addEventListener('click', function () {
          roadmapWrapper.scrollBy({ left: 250, behavior: 'smooth' });
        });
      }

      // Hide arrows if reached start or end
      const updateArrows = () => {
        if (scrollLeftBtn) {
          scrollLeftBtn.style.opacity = roadmapWrapper.scrollLeft > 10 ? '1' : '0.2';
          scrollLeftBtn.style.pointerEvents = roadmapWrapper.scrollLeft > 10 ? 'auto' : 'none';
        }
        if (scrollRightBtn) {
          const maxScroll = roadmapWrapper.scrollWidth - roadmapWrapper.clientWidth;
          scrollRightBtn.style.opacity = roadmapWrapper.scrollLeft < maxScroll - 10 ? '1' : '0.2';
          scrollRightBtn.style.pointerEvents = roadmapWrapper.scrollLeft < maxScroll - 10 ? 'auto' : 'none';
        }
      };

      roadmapWrapper.addEventListener('scroll', updateArrows, { passive: true });
      window.addEventListener('resize', updateArrows, { passive: true });
      setTimeout(updateArrows, 150);
    }
  }

  initRoadmapScroll();

})();

/* Analytics: WhatsApp and phone clicks */
document.addEventListener('click', function (e) {
  var link = e.target.closest && e.target.closest('a[href^="https://wa.me/"], a[href^="tel:"]');
  if (!link || !window.dataLayer) return;
  var area = link.closest('.top-bar, header, footer, section');
  window.dataLayer.push({
    event: link.href.indexOf('wa.me') > -1 ? 'whatsapp_click' : 'phone_click',
    cta_location: area ? (area.id || area.className.split(' ')[0]) : ''
  });
});

/* --- js/animations.js --- */
/* ============================================================
   Scroll Reveal Animations   Intersection Observer
   Applies .revealed class when elements enter viewport.
   Respects prefers-reduced-motion.
   ============================================================ */

(function () {
  'use strict';

  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  if (reducedMotion) {
    // Make everything visible immediately
    document.querySelectorAll('.reveal, .reveal-left, .reveal-right').forEach(function (el) {
      el.classList.add('revealed');
    });
    return;
  }

  // IntersectionObserver for reveal-on-scroll
  const observer = new IntersectionObserver(
    function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('revealed');
          observer.unobserve(entry.target);
        }
      });
    },
    {
      threshold: 0.08,
      rootMargin: '0px 0px -30px 0px'
    }
  );

  document.querySelectorAll('.reveal, .reveal-left, .reveal-right').forEach(function (el) {
    observer.observe(el);
  });

})();


/* --- js/cookie-consent.js --- */
/* ============================================================
   Cookie Consent Banner — JS
   Stores the visitor's choice in localStorage for 365 days and
   applies it to Google Consent Mode v2 (defaults are set inline
   in each page <head>).
   Zoho PageSense (enquiry and visit analytics) loads:
   - after "Accept", everywhere;
   - before any choice, only outside the UK/EEA/Switzerland
     (detected from the device time zone), mirroring the
     Consent Mode defaults;
   - never after "Essential only".
   ============================================================ */

(function () {
  'use strict';

  var COOKIE_KEY = 'zudo_cookie_consent';
  var COOKIE_EXPIRY_DAYS = 365;
  var PAGESENSE_SRC = 'https://cdn-in.pagesense.io/js/zudoworks/a082c937db01490eb591882d194fbe5a.js';

  function read(key) {
    try { return localStorage.getItem(key); } catch (e) { return null; }
  }

  function write(key, value) {
    try { localStorage.setItem(key, value); } catch (e) { }
  }

  // UK, EEA and Swiss visitors must opt in before analytics run
  function needsOptIn() {
    try {
      var tz = Intl.DateTimeFormat().resolvedOptions().timeZone || '';
      return /^(Europe|Atlantic\/(Reykjavik|Canary|Madeira|Azores|Faroe))\//.test(tz);
    } catch (e) {
      return true;
    }
  }

  function getConsent() {
    return read(COOKIE_KEY);
  }

  function hasConsentExpired() {
    var storedDate = read(COOKIE_KEY + '_date');
    if (!storedDate) return false;
    var daysSince = (Date.now() - parseInt(storedDate, 10)) / (1000 * 60 * 60 * 24);
    return daysSince > COOKIE_EXPIRY_DAYS;
  }

  function loadPageSense() {
    if (document.getElementById('pagesense-script')) return;
    var s = document.createElement('script');
    s.id = 'pagesense-script';
    s.async = true;
    s.src = PAGESENSE_SRC;
    document.head.appendChild(s);
  }

  function applyConsent(value) {
    var granted = value === 'accepted';
    if (typeof window.gtag === 'function') {
      window.gtag('consent', 'update', { analytics_storage: granted ? 'granted' : 'denied' });
    }
    if (granted) loadPageSense();
  }

  function setConsent(value) {
    write(COOKIE_KEY, value);
    write(COOKIE_KEY + '_date', Date.now().toString());
    applyConsent(value);
  }

  function hideBanner(banner) {
    banner.classList.remove('visible');
    setTimeout(function () {
      banner.remove();
    }, 500);
  }

  function showBanner() {
    if (document.getElementById('cookie-consent')) return;

    var banner = document.createElement('div');
    banner.id = 'cookie-consent';
    banner.setAttribute('role', 'region');
    banner.setAttribute('aria-label', 'Cookie preferences');
    banner.innerHTML = [
      '<div class="cookie-inner">',
      '  <div class="cookie-icon" aria-hidden="true">🍪</div>',
      '  <div class="cookie-actions">',
      '    <button type="button" id="cookie-accept">Accept All</button>',
      '    <button type="button" id="cookie-decline">Essential Only</button>',
      '  </div>',
      '  <div class="cookie-text">',
      '    <p>We use essential cookies to run this site. With your consent we also use analytics cookies (Google Analytics and Zoho PageSense) to understand how the site is used. Where the law requires it, analytics stay off until you accept. See our <a href="/privacy/">Privacy Policy</a>.</p>',
      '  </div>',
      '</div>'
    ].join('');

    document.body.appendChild(banner);

    requestAnimationFrame(function () {
      requestAnimationFrame(function () {
        banner.classList.add('visible');
      });
    });

    document.getElementById('cookie-accept').addEventListener('click', function () {
      setConsent('accepted');
      hideBanner(banner);
    });

    document.getElementById('cookie-decline').addEventListener('click', function () {
      setConsent('declined');
      hideBanner(banner);
    });
  }

  // Lets a "Cookie settings" link reopen the banner: onclick="zudoCookieSettings()"
  window.zudoCookieSettings = showBanner;

  function init() {
    var consent = getConsent();
    if (consent && !hasConsentExpired()) {
      if (consent === 'accepted') loadPageSense();
      return;
    }
    if (!needsOptIn()) loadPageSense();
    showBanner();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();

/* --- js/booking.js --- */
/* ============================================================
   Zoho Bookings Dialog
   Opens #custom-bookings-modal from any [data-booking] link or
   button (links fall back to /contact/ without JavaScript), loads the Zoho Bookings embed script on first
   open only, closes on Escape or backdrop click,
   and returns focus to the button that opened it.
   ============================================================ */

(function () {
  'use strict';

  var EMBED_SRC = 'https://bookings.nimbuspop.com/assets/embed.js';
  var BOOKING_URL = 'https://zudocroporation.zohobookings.in/portal-embed#/471882000000032065';

  var modal = document.getElementById('custom-bookings-modal');
  var closeBtn = document.getElementById('close-bookings-modal');
  var triggers = document.querySelectorAll('[data-booking]');
  if (!modal || !triggers.length) return;

  var embedded = false;
  var scriptRequested = false;
  var lastTrigger = null;

  function embed() {
    if (embedded || typeof window.Bookings === 'undefined') return;
    window.Bookings.inlineEmbed({
      url: BOOKING_URL,
      parent: '#inline-container',
      height: '100%'
    });
    embedded = true;
  }

  function loadEmbedScript() {
    if (scriptRequested) return;
    scriptRequested = true;
    var s = document.createElement('script');
    s.src = EMBED_SRC;
    s.async = true;
    s.onload = embed;
    document.body.appendChild(s);
  }

  function open(e) {
    if (e) e.preventDefault();
    lastTrigger = e ? e.currentTarget : null;
    modal.hidden = false;
    document.body.style.overflow = 'hidden';
    if (window.dataLayer) window.dataLayer.push({ event: 'book_call_click', cta_location: lastTrigger ? (lastTrigger.closest('section, header, footer, .top-bar') || {}).id || lastTrigger.className : '' });
    if (typeof window.Bookings !== 'undefined') embed(); else loadEmbedScript();
    if (closeBtn) closeBtn.focus();
  }

  function close() {
    modal.hidden = true;
    document.body.style.overflow = '';
    if (lastTrigger) lastTrigger.focus();
  }

  triggers.forEach(function (btn) {
    btn.setAttribute('aria-haspopup', 'dialog');
    btn.addEventListener('click', open);
  });

  if (closeBtn) closeBtn.addEventListener('click', close);

  modal.addEventListener('click', function (e) {
    if (e.target === modal) close();
  });

  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && !modal.hidden) close();
  });
})();

/* --- js/salesiq.js --- */
/* ============================================================
   Zoho SalesIQ Loader
   Loads the chat widget on the visitor's first interaction or
   after 6 seconds, so it never competes with the first render.
   ============================================================ */

(function () {
  'use strict';

  var WIDGET_SRC = 'https://salesiq.zohopublic.in/widget?wc=siq41d5faa948254fbe80c22c34c3b718451e4896b7c5f3c1a47f09184669bc09db';
  var EVENTS = ['pointerdown', 'keydown', 'scroll', 'touchstart'];
  var loaded = false;

  function load() {
    if (loaded) return;
    loaded = true;
    EVENTS.forEach(function (evt) { window.removeEventListener(evt, load); });

    window.$zoho = window.$zoho || {};
    window.$zoho.salesiq = window.$zoho.salesiq || { ready: function () { } };

    var s = document.createElement('script');
    s.id = 'zsiqscript';
    s.src = WIDGET_SRC;
    s.defer = true;
    document.body.appendChild(s);
  }

  EVENTS.forEach(function (evt) {
    window.addEventListener(evt, load, { once: true, passive: true });
  });
  window.addEventListener('load', function () { setTimeout(load, 6000); });
})();

/* --- js/media.js --- */
/* ============================================================
   Media: image lightbox and click-to-play YouTube
   - <a href="big.webp" data-lightbox="Caption"> opens the image
     full size in a dialog; Escape, the close button or a click
     on the backdrop closes it and returns focus.
   - <button data-youtube="VIDEO_ID"> swaps itself for a
     youtube-nocookie player only when clicked, so nothing from
     YouTube loads until the visitor asks for it.
   ============================================================ */

(function () {
  'use strict';

  var dialog, img, caption, lastTrigger;

  function buildDialog() {
    dialog = document.createElement('div');
    dialog.className = 'lightbox';
    dialog.setAttribute('role', 'dialog');
    dialog.setAttribute('aria-modal', 'true');
    dialog.setAttribute('aria-label', 'Image viewer');
    dialog.hidden = true;
    dialog.innerHTML =
      '<figure class="lightbox-figure">' +
      '<button type="button" class="lightbox-close" aria-label="Close image">&times;</button>' +
      '<img alt="">' +
      '<figcaption></figcaption>' +
      '</figure>';
    document.body.appendChild(dialog);
    img = dialog.querySelector('img');
    caption = dialog.querySelector('figcaption');
    dialog.addEventListener('click', function (e) {
      if (e.target === dialog || e.target.classList.contains('lightbox-close')) close();
    });
  }

  function open(trigger) {
    if (!dialog) buildDialog();
    lastTrigger = trigger;
    var thumb = trigger.querySelector('img');
    img.src = trigger.getAttribute('href');
    img.alt = thumb ? thumb.alt : '';
    caption.textContent = trigger.getAttribute('data-lightbox') || '';
    dialog.hidden = false;
    document.body.style.overflow = 'hidden';
    dialog.querySelector('.lightbox-close').focus();
  }

  function close() {
    dialog.hidden = true;
    document.body.style.overflow = '';
    if (lastTrigger) lastTrigger.focus();
  }

  document.addEventListener('click', function (e) {
    var t = e.target.closest && e.target.closest('a[data-lightbox]');
    if (t) {
      e.preventDefault();
      open(t);
      return;
    }
    var yt = e.target.closest && e.target.closest('button[data-youtube]');
    if (yt) {
      var frame = document.createElement('iframe');
      frame.src = 'https://www.youtube-nocookie.com/embed/' + yt.getAttribute('data-youtube') + '?autoplay=1&rel=0';
      frame.title = yt.getAttribute('aria-label') || 'YouTube video';
      frame.allow = 'autoplay; encrypted-media; picture-in-picture; fullscreen';
      frame.allowFullscreen = true;
      frame.className = 'video-frame';
      yt.replaceWith(frame);
    }
  });

  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && dialog && !dialog.hidden) close();
  });
})();
