/* Generated by tools/build.py from js/*.js. Do not edit. */
/* --- js/main.js --- */
/* ============================================================
   Main JavaScript   Navbar, Mobile Menu, Smooth Scroll,
   Scroll Progress, FAQ Accordion, Roadmap Scroll
   ============================================================ */

(function () {
  'use strict';

  // -- Navbar scroll behavior --------------------------------
  const navbar = document.querySelector('.navbar');

  function handleNavbarScroll() {
    if (!navbar) return;
    if (window.scrollY > 50) {
      navbar.classList.add('scrolled');
    } else {
      navbar.classList.remove('scrolled');
    }
  }

  window.addEventListener('scroll', handleNavbarScroll, { passive: true });
  handleNavbarScroll(); // initial check

  // -- Scroll Progress Bar -----------------------------------
  const progressBar = document.getElementById('scrollProgress');

  function updateScrollProgress() {
    if (!progressBar) return;
    const scrollTop = window.scrollY;
    const docHeight = document.documentElement.scrollHeight - window.innerHeight;
    if (docHeight <= 0) return;
    const scrollPercent = (scrollTop / docHeight) * 100;
    progressBar.style.width = scrollPercent + '%';
  }

  window.addEventListener('scroll', updateScrollProgress, { passive: true });
  updateScrollProgress();

  // -- Mobile menu toggle ------------------------------------
  const toggle = document.querySelector('.navbar-toggle');
  const mobileNav = document.querySelector('.navbar-nav');

  if (toggle && mobileNav) {
    toggle.addEventListener('click', function () {
      const isOpen = toggle.classList.toggle('open');
      mobileNav.classList.toggle('open');
      toggle.setAttribute('aria-expanded', isOpen);
      document.body.style.overflow = isOpen ? 'hidden' : '';
    });

    // Close mobile menu when a link is clicked
    mobileNav.querySelectorAll('.navbar-link').forEach(function (link) {
      link.addEventListener('click', function () {
        toggle.classList.remove('open');
        mobileNav.classList.remove('open');
        toggle.setAttribute('aria-expanded', 'false');
        document.body.style.overflow = '';
      });
    });

    // Close on escape key
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && toggle.classList.contains('open')) {
        toggle.classList.remove('open');
        mobileNav.classList.remove('open');
        toggle.setAttribute('aria-expanded', 'false');
        document.body.style.overflow = '';
        toggle.focus();
      }
    });
  }

  // -- Smooth scroll for anchor links ------------------------
  document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
    anchor.addEventListener('click', function (e) {
      const targetId = this.getAttribute('href');
      if (targetId === '#') return;
      const target = document.querySelector(targetId);
      if (target) {
        e.preventDefault();
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });

  // -- FAQ Accordion Toggle -------------------------------
  function initFaqAccordion() {
    const faqItems = document.querySelectorAll('.faq-question');
    if (!faqItems.length) return;

    faqItems.forEach(function (btn, i) {
      var item = btn.closest('.faq-item');
      var answer = item && item.querySelector('.faq-answer');
      if (answer) {
        if (!answer.id) answer.id = 'faq-answer-' + (i + 1);
        btn.setAttribute('aria-controls', answer.id);
      }
      btn.setAttribute('aria-expanded', item && item.classList.contains('active') ? 'true' : 'false');

      // Native <button> already handles Enter and Space
      btn.addEventListener('click', function () {
        var isOpen = item.classList.toggle('active');
        btn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
        if (answer) {
          answer.style.display = isOpen ? 'block' : 'none';
        }
      });
    });
  }

  initFaqAccordion();

  // -- Roadmap Scroll Indicators ------------------------------
  function initRoadmapScroll() {
    const roadmapWrapper = document.querySelector('.roadmap-wrapper');
    const scrollLeftBtn = document.querySelector('.roadmap-scroll-indicator.left');
    const scrollRightBtn = document.querySelector('.roadmap-scroll-indicator.right');

    if (roadmapWrapper && (scrollLeftBtn || scrollRightBtn)) {
      if (scrollLeftBtn) {
        scrollLeftBtn.addEventListener('click', function () {
          roadmapWrapper.scrollBy({ left: -250, behavior: 'smooth' });
        });
      }
      if (scrollRightBtn) {
        scrollRightBtn.addEventListener('click', function () {
          roadmapWrapper.scrollBy({ left: 250, behavior: 'smooth' });
        });
      }

      // Hide arrows if reached start or end
      const updateArrows = () => {
        if (scrollLeftBtn) {
          scrollLeftBtn.style.opacity = roadmapWrapper.scrollLeft > 10 ? '1' : '0.2';
          scrollLeftBtn.style.pointerEvents = roadmapWrapper.scrollLeft > 10 ? 'auto' : 'none';
        }
        if (scrollRightBtn) {
          const maxScroll = roadmapWrapper.scrollWidth - roadmapWrapper.clientWidth;
          scrollRightBtn.style.opacity = roadmapWrapper.scrollLeft < maxScroll - 10 ? '1' : '0.2';
          scrollRightBtn.style.pointerEvents = roadmapWrapper.scrollLeft < maxScroll - 10 ? 'auto' : 'none';
        }
      };

      roadmapWrapper.addEventListener('scroll', updateArrows, { passive: true });
      window.addEventListener('resize', updateArrows, { passive: true });
      setTimeout(updateArrows, 150);
    }
  }

  initRoadmapScroll();

})();

/* --- js/animations.js --- */
/* ============================================================
   Scroll Reveal Animations   Intersection Observer
   Applies .revealed class when elements enter viewport.
   Respects prefers-reduced-motion.
   ============================================================ */

(function () {
  'use strict';

  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  if (reducedMotion) {
    // Make everything visible immediately
    document.querySelectorAll('.reveal, .reveal-left, .reveal-right').forEach(function (el) {
      el.classList.add('revealed');
    });
    return;
  }

  // IntersectionObserver for reveal-on-scroll
  const observer = new IntersectionObserver(
    function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('revealed');
          observer.unobserve(entry.target);
        }
      });
    },
    {
      threshold: 0.08,
      rootMargin: '0px 0px -30px 0px'
    }
  );

  document.querySelectorAll('.reveal, .reveal-left, .reveal-right').forEach(function (el) {
    observer.observe(el);
  });

})();


/* --- js/counter.js --- */
/* ============================================================
   Animated Number Counter   Counts from 0 to target value
   Triggered by Intersection Observer when element scrolls
   into view. Respects prefers-reduced-motion.
   
   Usage: Add data-count="100" to any element.
   The text content will animate from 0 to 100.
   Supports optional data-count-suffix="+" etc.
   ============================================================ */

(function () {
  'use strict';

  const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const counters = document.querySelectorAll('[data-count]');

  if (!counters.length) return;

  // Easing function: ease-out cubic
  function easeOutCubic(t) {
    return 1 - Math.pow(1 - t, 3);
  }

  function animateCounter(el) {
    const target = parseInt(el.getAttribute('data-count'), 10);
    const suffix = el.getAttribute('data-count-suffix') || '';
    const prefix = el.getAttribute('data-count-prefix') || '';
    const duration = 1800; // ms
    const startTime = performance.now();

    if (reducedMotion || isNaN(target)) {
      el.textContent = prefix + target + suffix;
      return;
    }

    function update(currentTime) {
      const elapsed = currentTime - startTime;
      const progress = Math.min(elapsed / duration, 1);
      const eased = easeOutCubic(progress);
      const currentValue = Math.round(eased * target);

      el.textContent = prefix + currentValue + suffix;

      if (progress < 1) {
        requestAnimationFrame(update);
      }
    }

    requestAnimationFrame(update);
  }

  // Use IntersectionObserver to trigger animation on scroll
  const observer = new IntersectionObserver(
    function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          animateCounter(entry.target);
          observer.unobserve(entry.target);
        }
      });
    },
    {
      threshold: 0.3,
      rootMargin: '0px 0px -20px 0px'
    }
  );

  counters.forEach(function (counter) {
    // Set initial value to 0 (or prefix + 0 + suffix)
    if (!reducedMotion) {
      const suffix = counter.getAttribute('data-count-suffix') || '';
      const prefix = counter.getAttribute('data-count-prefix') || '';
      counter.textContent = prefix + '0' + suffix;
    }
    observer.observe(counter);
  });

})();


/* --- js/cookie-consent.js --- */
/* ============================================================
   Cookie Consent Banner — JS
   Stores the visitor's choice in localStorage for 365 days and
   applies it to Google Consent Mode v2 (defaults are set inline
   in each page <head>). Zoho PageSense loads only after "Accept".
   "Accept" = analytics allowed. "Essential only" = analytics off.
   ============================================================ */

(function () {
  'use strict';

  var COOKIE_KEY = 'zudo_cookie_consent';
  var COOKIE_EXPIRY_DAYS = 365;
  var PAGESENSE_SRC = 'https://cdn-in.pagesense.io/js/zudoworks/a082c937db01490eb591882d194fbe5a.js';

  function read(key) {
    try { return localStorage.getItem(key); } catch (e) { return null; }
  }

  function write(key, value) {
    try { localStorage.setItem(key, value); } catch (e) { }
  }

  function getConsent() {
    return read(COOKIE_KEY);
  }

  function hasConsentExpired() {
    var storedDate = read(COOKIE_KEY + '_date');
    if (!storedDate) return false;
    var daysSince = (Date.now() - parseInt(storedDate, 10)) / (1000 * 60 * 60 * 24);
    return daysSince > COOKIE_EXPIRY_DAYS;
  }

  function loadPageSense() {
    if (document.getElementById('pagesense-script')) return;
    var s = document.createElement('script');
    s.id = 'pagesense-script';
    s.async = true;
    s.src = PAGESENSE_SRC;
    document.head.appendChild(s);
  }

  function applyConsent(value) {
    var granted = value === 'accepted';
    if (typeof window.gtag === 'function') {
      window.gtag('consent', 'update', { analytics_storage: granted ? 'granted' : 'denied' });
    }
    if (granted) loadPageSense();
  }

  function setConsent(value) {
    write(COOKIE_KEY, value);
    write(COOKIE_KEY + '_date', Date.now().toString());
    applyConsent(value);
  }

  function hideBanner(banner) {
    banner.classList.remove('visible');
    setTimeout(function () {
      banner.remove();
    }, 500);
  }

  function showBanner() {
    if (document.getElementById('cookie-consent')) return;

    var banner = document.createElement('div');
    banner.id = 'cookie-consent';
    banner.setAttribute('role', 'region');
    banner.setAttribute('aria-label', 'Cookie preferences');
    banner.innerHTML = [
      '<div class="cookie-inner">',
      '  <div class="cookie-icon" aria-hidden="true">🍪</div>',
      '  <div class="cookie-actions">',
      '    <button type="button" id="cookie-accept">Accept All</button>',
      '    <button type="button" id="cookie-decline">Essential Only</button>',
      '  </div>',
      '  <div class="cookie-text">',
      '    <p>We use essential cookies to run this site. With your consent we also use analytics cookies (Google Analytics and Zoho PageSense) to understand how the site is used. Where the law requires it, analytics stay off until you accept. See our <a href="/privacy-policy.html">Privacy Policy</a>.</p>',
      '  </div>',
      '</div>'
    ].join('');

    document.body.appendChild(banner);

    requestAnimationFrame(function () {
      requestAnimationFrame(function () {
        banner.classList.add('visible');
      });
    });

    document.getElementById('cookie-accept').addEventListener('click', function () {
      setConsent('accepted');
      hideBanner(banner);
    });

    document.getElementById('cookie-decline').addEventListener('click', function () {
      setConsent('declined');
      hideBanner(banner);
    });
  }

  // Lets a "Cookie settings" link reopen the banner: onclick="zudoCookieSettings()"
  window.zudoCookieSettings = showBanner;

  function init() {
    var consent = getConsent();
    if (consent && !hasConsentExpired()) {
      if (consent === 'accepted') loadPageSense();
      return;
    }
    showBanner();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }

})();

/* --- js/salesiq.js --- */
/* ============================================================
   Zoho SalesIQ Loader
   Loads the chat widget on the visitor's first interaction or
   after 6 seconds, so it never competes with the first render.
   ============================================================ */

(function () {
  'use strict';

  var WIDGET_SRC = 'https://salesiq.zohopublic.in/widget?wc=siq41d5faa948254fbe80c22c34c3b718451e4896b7c5f3c1a47f09184669bc09db';
  var EVENTS = ['pointerdown', 'keydown', 'scroll', 'touchstart'];
  var loaded = false;

  function load() {
    if (loaded) return;
    loaded = true;
    EVENTS.forEach(function (evt) { window.removeEventListener(evt, load); });

    window.$zoho = window.$zoho || {};
    window.$zoho.salesiq = window.$zoho.salesiq || { ready: function () { } };

    var s = document.createElement('script');
    s.id = 'zsiqscript';
    s.src = WIDGET_SRC;
    s.defer = true;
    document.body.appendChild(s);
  }

  EVENTS.forEach(function (evt) {
    window.addEventListener(evt, load, { once: true, passive: true });
  });
  window.addEventListener('load', function () { setTimeout(load, 6000); });
})();
