# Review notes per article. insights_gen.py copies these into blog/.automation-history.json, which is the
# index an automated run reads first, so it does not need to open every article.
#
#   checked     date the facts were last verified against the sources ('' = never verified by a review run)
#   volatility  how quickly the facts go out of date: 'high' re-check after 14 days, 'medium' 45, 'low' 120
#   facts       the specific claims that can expire or change
#   sources     where to verify them
#   cover       layout and colour theme of the cover image, so new covers can be made to look different
WATCH = {
    'zoho-crm-vs-hubspot': dict(
        cover='panel-compare / blue',
        checked='2026-10-09', volatility='high',
        facts=['Zoho CRM free edition: up to 3 users', 'HubSpot free tools: up to 2 users',
               'HubSpot Professional and Enterprise have a required one-time onboarding fee',
               'HubSpot Marketing Hub price depends on marketing contacts',
               'Sequences not in HubSpot Free or Starter; Starter workflows limited',
               'Zoho CRM: Blueprint from Professional; Zia and sandbox from Enterprise'],
        sources=['https://www.zoho.com/crm/zohocrm-pricing.html', 'https://www.zoho.com/crm/comparison.html',
                 'https://www.hubspot.com/pricing/sales', 'https://www.hubspot.com/pricing/marketing']),
    'zoho-mcp-claude-chatgpt': dict(
        cover='steps / navy',
        checked='2026-10-09', volatility='high',
        facts=['Zoho MCP is free to use for now', 'MCP calls follow each app\'s normal API limits',
               'Two modes: Authorize on Demand, Authorize via Connections (Super Admin only)',
               'Logs kept 30 days', 'About 100 tools per server recommended, 300 maximum',
               'Claude custom connectors: Pro, Max, Team, Enterprise; Owners add on Team and Enterprise',
               'ChatGPT write actions in beta on Business, Enterprise, Edu; Pro read and fetch only',
               'Zoho CRM publishes four ready-made MCP servers', 'Menu names in the six setup steps'],
        sources=['https://www.zoho.com/mcp/', 'https://help.zoho.com/portal/en/kb/mcp/help-support/articles/zoho-mcp-faq',
                 'https://help.zoho.com/portal/en/kb/mcp/implementation-guide/articles/zoho-mcp-implementation-guide',
                 'https://www.zoho.com/crm/developer/docs/mcp/setup/claude.html',
                 'https://support.claude.com/en/articles/11175166-getting-started-with-custom-connectors-using-remote-mcp',
                 'https://help.openai.com/en/articles/12584461-developer-mode-and-full-mcp-connectors-in-chatgpt']),
    'zoho-creator-vs-power-apps': dict(
        cover='table / amber',
        checked='', volatility='medium',
        facts=['Power Apps licensing: premium connectors, Dataverse and Power Pages need extra licences',
               'Zoho Creator plans include database, Deluge, portals and mobile apps; Creator is in Zoho One'],
        sources=['https://www.zoho.com/creator/pricing.html',
                 'https://www.microsoft.com/en-us/power-platform/products/power-apps/pricing']),
    'migrate-hubspot-salesforce-to-zoho-crm': dict(
        cover='arrows / blue',
        checked='', volatility='low',
        facts=['Import order and migration steps in Zoho CRM', 'Typical duration: two to four weeks for a small migration'],
        sources=['https://help.zoho.com/portal/en/kb/crm']),
    'zoho-crm-implementation-cost': dict(
        cover='number / navy',
        checked='', volatility='medium',
        facts=['Examples are in hours only; the Zudo Works rate is not published',
               'Hour ranges for starter, standard and advanced projects', 'Zoho CRM edition names'],
        sources=['https://www.zoho.com/crm/zohocrm-pricing.html', '/pricing/']),
    'deluge-script-examples': dict(
        cover='tiles / green',
        checked='', volatility='low',
        facts=['Deluge task names and syntax used in the ten examples'],
        sources=['https://www.zoho.com/deluge/help/']),
    'zoho-agentic-ai-hyperautomation': dict(
        cover='do and avoid / blue',
        checked='2026-10-09', volatility='high',
        facts=['Zoho CRM pricing page: AI agents from Standard, AI email insights from Professional, Zia predictions from Enterprise',
               'Zia Agents: Agent Studio (low-code) and Agent Store (prebuilt agents by Zoho), across 60+ Zoho apps',
               'Zia Agents is free as a service; you pay for LLM usage, with a free monthly token allowance on Zoho-hosted models',
               'Bring-your-own-key vendors for Zia Agents: OpenAI, Gemini, Claude',
               'Zia Chat announced 23 September 2026; availability not yet stated (add a section once it is generally available)'],
        sources=['https://www.zoho.com/zia/agents/', 'https://www.zoho.com/agents/pricing.html',
                 'https://www.zoho.com/crm/zohocrm-pricing.html', 'https://www.zoho.com/crm/comparison.html',
                 'https://www.zoho.com/press.html']),
    'zoho-analytics-agentic-data-foundations-2026': dict(
        cover='vertical steps / navy',
        checked='2026-10-09', volatility='medium',
        facts=['Zoho claims 500+ data sources', 'Data refresh rate: Basic 1/day, Standard 8/day, Premium 8/day, Enterprise 24/day',
               'LLM-powered Ask Zia agent on Premium and Enterprise only', 'Zoho Analytics has an MCP Server'],
        sources=['https://www.zoho.com/analytics/', 'https://www.zoho.com/analytics/pricing.html',
                 'https://zoho.com/analytics/help/zia/']),
    'zoho-partner-software-development': dict(
        cover='checklist / green',
        checked='', volatility='low',
        facts=['Advice only; few facts that expire'],
        sources=[]),
    'zoho-partner-program-explained': dict(
        cover='levels / amber',
        checked='2026-10-09', volatility='high',
        facts=['Partner tiers: Authorized, Advanced, Premium', 'US$5,000 revenue threshold for Authorized, within six months of onboarding',
               'Advanced above 400 points and Premium above 600 points out of 1,000',
               'Value score split: revenue 500, customer success 200, market readiness 200, Zoho engagement 100',
               'Tiers reassessed yearly; updated by January', 'Directory label "Find a Partner" and its URL',
               'Zudo Works\' own partner status (update the wording once it is approved)'],
        sources=['https://www.zoho.com/partners/partner-tiers.html', 'https://www.zoho.com/partners/find-zoho-partner.html']),
    'zoho-for-manufacturing': dict(
        cover='rows / green',
        checked='2026-10-09', volatility='high',
        facts=['Zoho Inventory KB still says manufacturing modules are not yet supported; composite items are assemblies and kits',
               'Zoho ERP is published for India only (en-in site, rupee pricing); no date announced for other countries',
               'Zoho ERP is not included in Zoho One; plans Standard, Premium, Custom; yearly transaction caps',
               'Zoho ERP help sections: BOM, manufacturing orders, job cards, shopfloor, work centers, subcontract manufacturing, quality',
               'Zoho ERP 2026 updates: work center calendar, manufacturing orders from sales orders, quality inspections on purchase receives',
               'Zoho Inventory, Creator and Flow are listed among Zoho One apps',
               'Creator manufacturing page positions Creator as an extension layer beside SAP, Oracle, Infor or NetSuite',
               'Vendor descriptions: MRPeasy (10 to 200 employees), Odoo, ERPNext (open source), Katana, TranZact (Indian MSMEs, Tally)'],
        sources=['https://www.zoho.com/us/inventory/kb/general-overview/zom-manufacturing-support.html',
                 'https://www.zoho.com/us/inventory/help/items/composite-items.html',
                 'https://www.zoho.com/en-in/erp/', 'https://www.zoho.com/en-in/erp/pricing/',
                 'https://www.zoho.com/en-in/erp/help/manufacturing-order/understanding-manufacturing-order.html',
                 'https://help.zoho.com/portal/en-gb/community/zoho-erp', 'https://www.zoho.com/press.html',
                 'https://www.zoho.com/creator/solutions/manufacturing/', 'https://www.zoho.com/one/applications/web.html',
                 'https://www.zoho.com/iot/industries/manufacturing.html', 'https://www.mrpeasy.com/',
                 'https://www.odoo.com/app/manufacturing-features', 'https://frappe.io/erpnext/open-source-manufacturing-erp-software',
                 'https://katanamrp.com/features/manufacturing/', 'https://letstranzact.ai/']),
    'zoho-flow-vs-deluge': dict(
        cover='split / blue and green',
        checked='2026-10-09', volatility='high',
        facts=['Zoho Flow: each executed action is one task; plans Free, Standard, Professional',
               'Flow Free plan: 100 tasks a month, 5 flows; polling 15 minutes (5 on Professional)',
               'Flow custom functions on Standard and Professional; history 30/60/90 days; on-prem agent on Professional',
               'Flow connects 1,000+ apps; Flow is listed among Zoho One apps',
               'Zoho CRM function timeouts: 10 s (button, related list, validation, REST API), 30 s (automation), 15 min (schedule)',
               'Statement limits: 5,000 (general Deluge page), 5,000 to 50,000 (Creator), 200,000 lines (CRM)',
               'Deluge: invokeurl response 5 MB; 75 function calls per function; CRM credits per function run',
               'Catalyst functions in Java, Node.js and Python'],
        sources=['https://www.zoho.com/flow/pricing.html', 'https://www.zoho.com/flow/',
                 'https://help.zoho.com/portal/en/kb/flow/user-guide/create-a-flow/actions-logic/articles/flow-control',
                 'https://www.zoho.com/deluge/help/limitations.html',
                 'https://www.zoho.com/crm/developer/docs/functions/limits-quotas.html',
                 'https://help.zoho.com/portal/en/kb/creator/developer-guide/limitations/articles/workflows-limitations',
                 'https://catalyst.zoho.com/', 'https://www.zoho.com/one/applications/web.html']),
}
